language: ruby

notifications:
  email: false

install:
  - gem install jekyll

script:
    - cd ..
    - git clone https://thiagohersan:$GHTOKEN@github.com/associacaosilo/interactivos.silo.org.br.git
    - cd interactivos.silo.org.br
    - sed -i -e 's/git@github.com:/https:\/\/thiagohersan:$GHTOKEN@github.com\//g' .gitmodules
    - ./deploy.sh

after_script:
  - cd ..
  - rm -rf interactivos.silo.org.br
